# Main config file for icon theme.
#theme = "hugo-icon"
baseURL = "https://sentiencenitd.in/"
languageCode = "en-US"
title = "Sentience"

# Metadata
[params]
  author = "Sentience NIT Dekhi"
  description = "Annual Techno Cultural Fest of National Institute of Technology, Delhi"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/outline_tit1.png"
  title = "Create awesome things for better web"
  description = "Lovingly hand-crafted by the fine folks at [FreeHTML5.co](http://freehtml5.co/)"

# Navigation section
[params.nav]
  events = "Events"
  talks = "Talks"
  team = "Team"
  timeline = "Timeline"
  sponsors = "Sponsors"
  contact = "Contact"
  details = "Details"
  # Include logo instead if HOME:
  logo = "images/sentience_black.png"
#About section
[params.about]
  enable = true


  [params.about.image1]
      img = "images/tt1.jpg"
  [params.about.image2]
      img = "images/home-min.jpg"

[params.sponsors]
	enable = true
	
	first = "Aptron.jpg"

	[[params.sponsors.sp]]
		img = "Bugsee.png"

	[[params.sponsors.sp]]
		img = "codeblocks.png"

	[[params.sponsors.sp]]
		img = "Groovenexus logo 220x70.png"


# Mission section
[params.mission]
  enable = false

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Resources"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Strategy"
    subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = true
  video = true
  vidlink = "https://www.youtube.com/watch?v=J3FFScpoeDs"
  title = "Events"
  description = "Gateway to Freeway. Discover yourself. "


  [[params.services.item]]

    icon = "icon-present"
    title = "Technical Events"
    img = "images/eve1.png"
    description = ""
	path = "/technicalevents"

		[[params.services.item.subcategory]]
			title = "Robotics"
			description = ""
			coverImage = "images/Robotics.jpg"

		[[params.services.item.subcategory]]
			title = "Coding"
			description = ""
			coverImage = "images/Coding.jpg"

  [[params.services.item]]

    icon = "icon-eye"
    title = "Cultural Events"
    img = "images/eve2.jpg"
    description = ""
	path = "/culturalevents"


		[[params.services.item.subcategory]]
			title = "Music"
			description = ""
			coverImage = "images/Music.jpg"

		[[params.services.item.subcategory]]
			title = "Art"
			description = ""
			coverImage = "images/Art.jpg"

		[[params.services.item.subcategory]]
			title = "Dance"
			description = ""
			coverImage = "images/Dance.jpg"

		[[params.services.item.subcategory]]
			title = "Dramatics"
			description = ""
			coverImage = "images/Dramatics.jpg"

		[[params.services.item.subcategory]]
			title = "Literature"
			description = ""
			coverImage = "images/Literature.jpg"

		[[params.services.item.subcategory]]
			title = "Fashion"
			description = ""
			coverImage = "images/Fashion.jpg"

[params.details]
  enable = true
  title = "Details"
  description = "Additional Information regarding the fest"

# Work section
[params.work]
  enable = true 

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

[params.timeline]
	enable = true
	title = "Timeline"

	[[params.timeline.day]]
		date = "Thursday 4th April, 2019"

		[[params.timeline.day.event]]
			starttime = "04:00 pm"
			eventname = "Opening Ceremony"

		[[params.timeline.day.event]]
			starttime = "05:00 pm"
			eventname = "Spotlight"
			link = "/culturalevents/spotlight"

		[[params.timeline.day.event]]
			starttime = "07:30 pm"
			eventname = "Sukhmanch"

	[[params.timeline.day]]
		date = "Friday 5th April, 2019"

		[[params.timeline.day.event]]
			starttime = "10:00 am"
			eventname = "NITDPL"
			link = "/technicalevents/nitdpl"

		[[params.timeline.day.event]]
			starttime = "10:30 am"
			eventname = "Goonj"
			link = "/culturalevents/goonj"

		[[params.timeline.day.event]]
			starttime = "12:00 pm"
			eventname = "End Game"
			link = "/technicalevents/endgame"

		[[params.timeline.day.event]]
			starttime = "01:00 pm"
			eventname = "Acapella"
			link = "/culturalevents/acapella"

		[[params.timeline.day.event]]
			starttime = "01:30 pm"
			eventname = "Kalachitra"
			link = "/culturalevents/kalachitra"

		[[params.timeline.day.event]]
			starttime = "03:00 pm"
			eventname = "Crack The Track"
			link = "/technicalevents/roborace"

		[[params.timeline.day.event]]
			starttime = "04:00 pm"
			eventname = "Mono Acting"
			link = ""

		[[params.timeline.day.event]]
			starttime = "04:30 pm"
			eventname = "Code Golf"
			link = "/technicalevents/codegolf"

		[[params.timeline.day.event]]
			starttime = "05:30 pm"
			eventname = "Color Splash"
			link = "/culturalevents/colorsplash"

		[[params.timeline.day.event]]
			starttime = "07:30 pm"
			eventname = "Kavi Samelan"
			link = ""

	[[params.timeline.day]]
		date = "Saturday 6th April, 2019"

		[[params.timeline.day.event]]
			starttime = "10:00 am"
			eventname = "Capture the flag"
			link = "/technicalevents/rootctf"

		[[params.timeline.day.event]]
			starttime = "10:30 am"
			eventname = "Lost Treasure"
			link = "/technicalevents/thelosttreasure"

		[[params.timeline.day.event]]
			starttime = "11:00 am"
			eventname = "Wordwar"
			link = "/culturalevents/wordwar"

		[[params.timeline.day.event]]
			starttime = "12:00 pm"
			eventname = "Upside Down"
			link = "/technicalevents/upsidedown"

		[[params.timeline.day.event]]
			starttime = "01:00 pm"
			eventname = "Solo Singing"
			link = ""

		[[params.timeline.day.event]]
			starttime = "02:00 pm"
			eventname = "The Quipster"
			link = "/culturalevents/thequipster"

		[[params.timeline.day.event]]
			starttime = "03:30 pm"
			eventname = "Triwizardry"
			link = "technicalevents/robosoccer+robosuperover+robobowling/"

		[[params.timeline.day.event]]
			starttime = "05:00 pm"
			eventname = "Breakfree"
			link = "/culturalevents/breakfree"

		[[params.timeline.day.event]]
			starttime = "07:30 pm"
			eventname = "EDM Night"
			link = ""

	[[params.timeline.day]]
		date = "Sunday 7th April, 2019"

		[[params.timeline.day.event]]
			starttime = "10:00 am"
			eventname = "Clash of Codes"
			link = "/technicalevents/clashofcodes"

		[[params.timeline.day.event]]
			starttime = "11:00 am"
			eventname = "Fight Club"
			link = "/technicalevents/fightclub2.0"

		[[params.timeline.day.event]]
			starttime = "11:30 am"
			eventname = "Battle of Bands"
			link = "/culturalevents/battleofbands"

		[[params.timeline.day.event]]
			starttime = "01:30 pm"
			eventname = "ODEssey: Poetry Slam"
			link = "/culturalevents/odessey"

		[[params.timeline.day.event]]
			starttime = "03:00 pm"
			eventname = "Reverse Coding"
			link = "/technicalevents/reversecoding"

		[[params.timeline.day.event]]
			starttime = "03:30 pm"
			eventname = "RubG"
			link = "/technicalevents/rubg"

		[[params.timeline.day.event]]
			starttime = "06:00 pm"
			eventname = "Theme Walk"
			link = "/culturalevents/runaway"

		[[params.timeline.day.event]]
			starttime = "07:30 pm"
			eventname = "Coke Studio"
			link = ""


# Team section
[params.team]
  enable = false
  title = "Meet The Team"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Alice Doe"
    position = "Chief overlord"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person2.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "John Doe"
    position = "Chief haranguer"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person3.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "The Sentience19 Team"
  message = "The backbones of Sentience 19"

	[[params.contact.section]]
		section = "Core Committee"

		[[params.contact.section.item]]
			name = "Amarjot Kaur"
			phno = "+91 98786 07155"
			position = "Core Head"

		[[params.contact.section.item]]
			name = "Arpan Singh"
			phno = "+91 90581 05581"
			position = "Core Head"

		[[params.contact.section.item]]
			name = "Ayush Pranav"
			phno = "+91 72890 17595"
			position = "Core Head"

	[[params.contact.section]]
		section = "Event Managment"

		[[params.contact.section.item]]
			name = "Nita Mathew" 
			phno = "+91 99996 25845"
			position = "Event Management"

		[[params.contact.section.item]]
			name = "Prathu Singh"
			phno = "+91 82218 07751"
			position = "Event Management"

		[[params.contact.section.item]]
			name = "Tanuj Yadav"
			phno = "+91 97167 55258"
			position = "Event Management"

	[[params.contact.section]]
		section = "Sponsorship"

		[[params.contact.section.item]]
			name = "Ojasvi"
			phno = "+91 99684 30077"
			position = "Sponsorship"

		[[params.contact.section.item]]
			name = "Sangeeta"
			phno = "+91 94902 19662"
			position = "Sponsorship"

	[[params.contact.section]]
		section = "Marketing"

		[[params.contact.section.item]]
			name = "Kritika"
			phno = "+91 85274 97717"
			position = "Marketing"

		[[params.contact.section.item]]
			name = "Suruchi"
			phno = "+91 88260 31570"
			position = "Marketing"

		[[params.contact.section.item]]
			name = "Shakya"
			phno = "+91 99997 67902"
			position = "Marketing"

	[[params.contact.section]]
		section = "Hospitality"

		[[params.contact.section.item]]
			name = "Pooja Singh"
			phno = "+91 95994 65488"
			position = "Hospitality"

		[[params.contact.section.item]]
			name = "Pooja Kumari"
			phno = "+91 85859 64798"
			position = "Hospitality"

	[[params.contact.section]]
		section = "Infrastructure & logistics"

		[[params.contact.section.item]]
			name = "Sudhir"
			phno = "+91 70233 84546"

		[[params.contact.section.item]]
			name = "Gurpreet"
			phno = "+91 85718 32001"

		[[params.contact.section.item]]
			name = "Aynjaney"
			phno = "+91 94702 87502"

	[[params.contact.section]]
		section = "Prize Distribution"

		[[params.contact.section.item]]
			name = "Ajay Meena"
			phno = "+91 99920 66748"

		[[params.contact.section.item]]
			name = "Ayushi"
			phno = "+91 97110 97535"

   # name_placeholder = "Your name"
  # email_placeholder = "Your email"
  # email_disclaimer = "We'll never share your email with anyone else."
  # message_placeholder = "Please enter a message."
  # button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2019 Sentience NIT Delhi. All Rights Reserved.</small></p>"
  facebook = "https://www.facebook.com/SentienceNITDelhi"
  instagram = "https://www.instagram.com/sentiencenitdelhi"
  
